#!/usr/bin/env python3
"""Generate authoritative protobuf golden wire vectors (T9.1 conformance corpus).

This script compiles ``conformance.proto`` with the bundled ``protoc`` (via
``grpc_tools.protoc``), then serializes a fixed set of representative messages
using Google's *authoritative* protobuf runtime. The exact wire bytes are
emitted as hex into ``corpus.golden`` (committed to the repo).

The MoonBit conformance test (``conformance_test.mbt``) embeds these same hex
vectors and asserts that this library's independent ``encode_typed`` produces —
and ``decode_typed`` consumes — byte-identical output, i.e. cross-implementation
interop with real protobuf.

Run offline (CI does not have network): ``python3 gen_corpus.py``.
Requires: ``pip install protobuf grpcio-tools``.
"""
from __future__ import annotations

import importlib.util
import struct
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROTO = HERE / "conformance.proto"
GOLDEN = HERE / "corpus.golden"


def _compile_and_import():
    """Compile conformance.proto and import the generated module."""
    out = Path(tempfile.mkdtemp(prefix="conf_pb_"))
    from grpc_tools import protoc

    rc = protoc.main(
        [
            "protoc",
            f"-I{HERE}",
            f"--python_out={out}",
            str(PROTO),
        ]
    )
    if rc != 0:
        raise SystemExit(f"protoc failed with code {rc}")
    gen = out / "conformance_pb2.py"
    spec = importlib.util.spec_from_file_location("conformance_pb2", gen)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def build_cases(pb):
    """Return a list of (case_name, message) covering all wire branches."""
    cases = []

    # all-fields: every scalar set to a non-default value so nothing is omitted.
    s = pb.Scalars()
    s.f_int32 = -1                 # negative int32 => 10-byte sign-extended varint
    s.f_int64 = -2                 # negative int64 varint
    s.f_uint32 = 4294967295        # uint32 max => 5-byte varint
    s.f_uint64 = 18446744073709551615  # uint64 max => 10-byte varint
    s.f_sint32 = -1                # zigzag => 1
    s.f_sint64 = -1234567890123    # zigzag large negative
    s.f_fixed32 = 305419896        # 0x12345678
    s.f_fixed64 = 1311768467463790320  # 0x123456789ABCDEF0
    s.f_sfixed32 = -2
    s.f_sfixed64 = -3
    s.f_float = 1.5
    s.f_double = -2.25
    s.f_bool = True
    s.f_string = "héllo"           # multibyte UTF-8
    s.f_bytes = bytes([0x00, 0xFF, 0x10])
    s.f_enum = pb.GREEN
    cases.append(("scalars_all", s))

    # int32 = 1 boundary (single-byte varint, only field present).
    s2 = pb.Scalars()
    s2.f_int32 = 1
    cases.append(("scalars_int32_one", s2))

    # nested message.
    n = pb.Nested()
    n.inner.f_int32 = 7
    n.inner.f_string = "x"
    n.tag = 42
    cases.append(("nested", n))

    # packed repeated (proto3 default packs numeric scalars).
    p = pb.Packed()
    p.vals.extend([1, 300, 70000])     # spans 1/2/3-byte varints
    p.svals.extend([-1, -2, 3])        # zigzag packed
    cases.append(("packed", p))

    # map with a single entry (deterministic byte order).
    m = pb.WithMap()
    m.m["k"] = 5
    cases.append(("map_single", m))

    return cases


def main():
    pb = _compile_and_import()
    lines = [
        "# Authoritative protobuf golden wire vectors (T9.1).",
        "# Generated by gen_corpus.py using Google protobuf runtime.",
        "# Format: <case_name> <message_type> <hex_wire_bytes>",
        f"# protobuf runtime: {__import__('google.protobuf').protobuf.__version__}",
    ]
    for name, msg in build_cases(pb):
        wire = msg.SerializeToString(deterministic=True)
        lines.append(f"{name} {type(msg).__name__} {wire.hex()}")
    GOLDEN.write_text("\n".join(lines) + "\n")
    print(f"wrote {GOLDEN} ({len(lines) - 4} cases)")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
